# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/bitcoin-daemon/values.yaml?ref_type=heads
FROM registry.gitlab.com/thorchain/devops/node-launcher:bitcoin-daemon-26.2@sha256:0080dd15a8a06312e2ca7bd5051ecc838275345ea98b285e7d66941225dd90c7
