# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/gaia-daemon/values.yaml?ref_type=heads
FROM registry.gitlab.com/thorchain/devops/node-launcher:gaia-daemon-19.2.0@sha256:b7c6735a96712e9350fbeb7f0b2fa72549c3ba3becd4278acb472735e22ff5f1
