# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/gateway/values.yaml?ref_type=heads
# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/gateway/templates/deployment.yaml?ref_type=heads
# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/gateway/templates/configmap.yaml?ref_type=heads
FROM nginx:1.25.3-alpine@sha256:2d2a2257c6e9d2e5b50d4fbeb436d8d2b55631c2a89935a425b417eb95212686

COPY nginx.conf /etc/nginx/nginx.conf