# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/litecoin-daemon/values.yaml?ref_type=heads
FROM registry.gitlab.com/thorchain/devops/node-launcher:litecoin-daemon-0.21.3@sha256:c1b50abe892771456bc4dcbc1f3617eb84fb89970c38d29880d9b0e2c2f8460a
