# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/avalanche-daemon/values.yaml?ref_type=heads
FROM registry.gitlab.com/thorchain/devops/node-launcher:avalanche-daemon-1.11.10@sha256:b269de2c8223c0c417dd4d9d994cdaa466e7eafa99268266d8ea9eb715e4199b
