# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/bitcoin-cash-daemon/values.yaml?ref_type=heads
FROM registry.gitlab.com/thorchain/devops/node-launcher:bitcoin-cash-daemon-27.1.0@sha256:79b701f54ce8ec034ec800f3a23e08a56e5d4e02a89cc1e7f17ee11326d0ec70
