# https://gitlab.com/thorchain/devops/node-launcher/-/blob/master/dogecoin-daemon/values.yaml?ref_type=heads
FROM registry.gitlab.com/thorchain/devops/node-launcher:dogecoin-daemon-1.14.7@sha256:496190c1ec8f4aefa8e894753016c73f3533176cd080bab1e6b45eca04a2a214
